### ISSUE TITLE
head disappearing when model swapping the lumberjack hat

### ISSUE THREAD

**Issue by Frooby91** [ArtimosPenguidor/animation-transmog#10]
I was using this plugin to spice up my woodcutting outfit while also getting the lumberjack bonus but whenever I changed my lumberjack hat into a saradomin halo my entire head would just vanish until I took off the lumberjack hat.  This might be an issue with hats that cover your head it seems?

**Comment by geheur** [comment]
I don't think this plugin can transmog gear. Were you looking for https://github.com/geheur/weapon-animation-replacer? If so you have to go to hide/show slots in the item search and pick show hair and show jaw.

**Comment by ArtimosPenguidor** [comment]
Yeah thanks @geheur. My plugin is strictly for animations, so @geheur's plugin is what you're looking for.
