### ISSUE TITLE
Love the plugin! 

### ISSUE THREAD

**Issue by ktcc123** [ArtimosPenguidor/animation-transmog#3]
Hey just wanna say I love this plugin! Adding some cosmetic feature into this game is a nice change once in a while. Is there by any chance that you can add more teleportation transmogs into the plugin? So far there are only 3 and they are very similar in nature. Would love to see a new variety. Something like the desert amulet teleport would be aweome

**Comment by ArtimosPenguidor** [comment]
I have added 6 new teleport effects with this update https://github.com/runelite/plugin-hub/pull/3262

Once it's merged in you'll be able to use them.

Thanks!
Nick
