### ISSUE TITLE
Cursed banana animation repeats too early?

### ISSUE THREAD

**Issue by BluntOSRS** [ArtimosPenguidor/animation-transmog#5]
Hi, I've been looking for some fixes to this issue, to no avail.

I'm trying to get the cursed banana animation to play fully, but it repeats early and it looks a bit off.
I'm wondering if there is a fix for this, or if you plan to fix it? Great plugin by the way.

Thanks,
-B

**Comment by ArtimosPenguidor** [comment]
A PR has been made to add this change into the game, I'll close the ticket with it gets merged in.

**Comment by ArtimosPenguidor** [comment]
This update is now in the latest version of the plugin.
