### ISSUE TITLE
Ghommal's Hilt?

### ISSUE THREAD

**Issue by RSensei** [ArtimosPenguidor/animation-transmog#6]
Hello! I love the plug in, is there a way to add the Ghommal's Hilt teleport to the teleport list? Thank you!

**Comment by ArtimosPenguidor** [comment]
Hey, glad you like the plugin! Yes I can that no problem to the list of teleport animations.

**Comment by RSensei** [comment]
Thank you so much!!!

**Comment by ArtimosPenguidor** [comment]
I just wanted to update this issue as it took me a very long time to get around to updating the plugin. This has been added to the list of teleport options.
