### ISSUE TITLE
Death animation transmog.

### ISSUE THREAD

**Issue by geheur** [ArtimosPenguidor/animation-transmog#8]
It would be cool if we could replace the death animation (836) with 837 (838 also maybe, it's a static version of the end of 837).
![N1fFPigqdc](https://user-images.githubusercontent.com/41499327/148885895-e51d1660-f82e-4312-b475-1de1f0fd856c.gif)

**Comment by ArtimosPenguidor** [comment]
These are great ideas. Unfortunately my macbook (where I've done all my work on the plugin) is currently broken and am working on getting it repaired soon.

I'll look into adding these updates after I have a working macbook again.

**Comment by ArtimosPenguidor** [comment]
A new Death animation config is to be added to the plugin with this PR https://github.com/runelite/plugin-hub/pull/3262

The effect you described will be set as the default called "Plank".

Thanks!
Nick
